name: Deploy to surge.sh

on:
    push:
        branches:
            - main

jobs:
    deploy:
        name: Deploy job
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Grab CDNs
              run: ./grab.sh
            - name: Deploy modern-education.surge.sh
              uses: dswistowski/surge-sh-action@v1
              with:
                  domain: 'modern-education.surge.sh'
                  project: 'web'
                  login: ${{ secrets.surge_login }}
                  token: ${{ secrets.surge_token }}
